### ISSUE TITLE
helm plugin install on latest fails with `mv: cannot stat 'releases/v0.13.0/bin/helm-s3': No such file or directory`

### ISSUE THREAD

**Issue by meatballhat** [hypnoglow/helm-s3#203] opened 2022-08-20 15:19 UTC
Hello and thank you for this lovely project! I'm seeing consistent failures to install the plugin at <del>0.13.0</del> <ins>latest, which at the time of this writing resolves to 0.13.0</ins>, e.g.:

```sh-session
$ helm plugin --debug install https://github.com/hypnoglow/helm-s3.git
[debug] vcs_installer.go:162: updating https://github.com/hypnoglow/helm-s3.git
[debug] vcs_installer.go:91: copying /home/dan/.cache/helm/plugins/https-github.com-hypnoglow-helm-s3.git to /home/dan/.local/share/helm/plugins/helm-s3.git
plugin_install.go:82: [debug] loading plugin from /home/dan/.local/share/helm/plugins/helm-s3.git
plugin.go:60: [debug] running install hook: /usr/bin/sh -c cd $HELM_PLUGIN_DIR; ./hack/install.sh
Downloading and installing helm-s3 v0.13.0 ...
Checksum is valid.
mv: cannot stat 'releases/v0.13.0/bin/helm-s3': No such file or directory
helm-s3 install hook failed. Please remove the plugin using 'helm plugin remove s3' and install again.
Error: plugin install hook for "s3" exited with error
helm.go:84: [debug] plugin install hook for "s3" exited with error
main.runHook
        helm.sh/helm/v3/cmd/helm/plugin.go:67
main.(*pluginInstallOptions).run
        helm.sh/helm/v3/cmd/helm/plugin_install.go:88
main.newPluginInstallCmd.func3
        helm.sh/helm/v3/cmd/helm/plugin_install.go:59
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.4.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1571
```

**Comment by meatballhat** [comment] 2022-08-20 15:25
notably, it appears that a `helms3` _is_ available:

```sh-session
$ find ~/.local/share/helm/plugins/helm-s3.git/releases/v0.13.0/bin -type f
/home/dan/.local/share/helm/plugins/helm-s3.git/releases/v0.13.0/bin/helms3
```

**Comment by meatballhat** [comment] 2022-08-20 15:54
IIUC it seems it's a mismatch between the `v0.13.0` artifacts and current `master` branch `./hack/install.sh` that's the problem 🤔  Maybe a `v0.14.0` bump (and relevant change to `plugin.yaml` will do the trick?

**Comment by rizwan-ops** [comment] 2022-08-20 23:59
I am getting same error, is there any solution for this?

**Comment by rizwan-ops** [comment] 2022-08-21 00:25
I reverted back to 0.12.0 version for now till the issue is fixed.

**Comment by OfirYaron** [comment] 2022-08-21 09:27
> I reverted back to` 0.12.0` version for now till the issue is fixed.

Having the same issue, how do you construct a .git url for a specific version?

**Comment by sheikhness** [comment] 2022-08-21 11:48
the problem is that in the binary package of 0.13.0, the directory name is "helms3" while the install.sh is looking for "helm-s3", with a hyphen. I think only maintainers of the repo can really fix. strangely, pinning the version with "helm plugin install <git url> --version=0.13.0" DOES seem to work.

**Comment by hypnoglow** [comment] 2022-08-21 16:20
Please prefer using specific version when installing the plugin. The changes in main branch are not released yet, so until the release you can workaround the issue with `helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.13.0`.

**Comment by HeWang-McK** [comment] 2022-08-22 02:13
In the future, when install s3 plugin, always need to specify the --version xxx ?

**Comment by gdajuk** [comment] 2022-08-23 09:36
Same issue on my side, downgrade to 0.12.0 fix the issue. Hopefully in 0.14.0 it will be fixed.

**Comment by abhijitpadegaonkar** [comment] 2022-08-23 18:10
Same issue on my side, downgrade to 0.12.0 fix the issue. Please fix.

**Comment by alop** [comment] 2022-08-23 20:21
This happens to coincide with a recent MacOS update for me:
```
$ helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.13.0
Downloading and installing helm-s3 v0.13.0 ...
Checksum is valid.
Installed plugin: s3

$ helm plugin list
NAME	VERSION	DESCRIPTION                                                                                
s3  	0.13.0 	Provides AWS S3 protocol support for charts and repos. https://github.com/hypnoglow/helm-s3

$ helm s3 
Error: fork/exec /Users/abelopez/Library/helm/plugins/helm-s3.git/bin/helms3: no such file or directory
```

**Comment by hypnoglow** [comment] 2022-08-23 23:41
The new version 0.14.0 is released, which should also fix installing the plugin without the `--version` flag.

**Closed by hypnoglow** 2022-08-23 23:41 UTC

**Comment by smoke** [comment] 2022-08-24 06:16
I confirm using `0.14.0` works like a charm without specifying the `--version`!
